name: gcc

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.b2_toolset }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        b2_toolset: [
          gcc-4.8,
          gcc-4.9,
          gcc-5,
          gcc-6,
          gcc-7,
          gcc-8,
          gcc-9
        ]

        include:
          - b2_toolset: gcc-4.8
            b2_cxxstd: 03,11
            version: "4.8"
          - b2_toolset: gcc-4.9
            b2_cxxstd: 03,11
            version: "4.9"
          - b2_toolset: gcc-5
            b2_cxxstd: 03,11,14
            version: "5"
          - b2_toolset: gcc-6
            b2_cxxstd: 03,11,14
            version: "6"
          - b2_toolset: gcc-7
            b2_cxxstd: 03,11,14,17
            version: "7"
          - b2_toolset: gcc-8
            b2_cxxstd: 03,11,14,17
            version: "8"
          - b2_toolset: gcc-9
            b2_cxxstd: 03,11,14,17,2a
            version: "9"

    steps:
      - name: Install
        run: |
          # gcc-4.8 is not available in Bionic anymore
          sudo add-apt-repository "deb http://dk.archive.ubuntu.com/ubuntu/ xenial main"
          sudo add-apt-repository "deb http://dk.archive.ubuntu.com/ubuntu/ xenial universe"
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt -q -y update
          sudo apt -q -y install g++-${{ matrix.version }} g++-${{ matrix.version }}-multilib

      - name: Set environment
        id: setenv
        run: |
          echo "::set-env name=BOOST_ROOT::$GITHUB_WORKSPACE/boost-root"

      - name: Clone boostorg/boost
        run: |
          git clone -b develop --depth 1 https://github.com/boostorg/boost.git $BOOST_ROOT
          cd $BOOST_ROOT
          git submodule update -q --init libs/headers
          git submodule update -q --init tools/boost_install
          git submodule update -q --init tools/boostdep
          git submodule update -q --init tools/build
          python tools/boostdep/depinst/depinst.py --include benchmark --include example --include examples --include tools libs/gil

      - name: Bootstrap boostorg/boost
        run: |
          gcc --version
          cd $BOOST_ROOT
          ./bootstrap.sh --with-toolset=gcc
          ./b2 headers
          test -f /usr/local/bin/b2 && rm -rf /usr/local/bin/b2
          test -f /usr/local/bin/bjam && rm -rf /usr/local/bin/bjam
          sudo cp $BOOST_ROOT/b2 /usr/local/bin/
          ls -l /usr/local/bin/b2
          b2 -v

      - uses: actions/checkout@v2

      - name: "Test 32-bit debug"
        run: |
          $BOOST_ROOT/b2 -sBOOST_ROOT=$BOOST_ROOT toolset=${{ matrix.b2_toolset }} cxxstd=${{ matrix.b2_cxxstd }} variant=debug address-model=32

      - name: "Test 32-bit release"
        run: |
          $BOOST_ROOT/b2 -sBOOST_ROOT=$BOOST_ROOT toolset=${{ matrix.b2_toolset }} cxxstd=${{ matrix.b2_cxxstd }} variant=release address-model=32

      - name: "Test 64-bit debug"
        run: |
          $BOOST_ROOT/b2 -sBOOST_ROOT=$BOOST_ROOT toolset=${{ matrix.b2_toolset }} cxxstd=${{ matrix.b2_cxxstd }} variant=debug address-model=64

      - name: "Test 64-bit release"
        run: |
          $BOOST_ROOT/b2 -sBOOST_ROOT=$BOOST_ROOT toolset=${{ matrix.b2_toolset }} cxxstd=${{ matrix.b2_cxxstd }} variant=release address-model=64
